### PR TITLE
Add CI for Rust

### PR DESCRIPTION
**Pull request by ahuston-0**

### CODE REVIEW

**Comment by ahuston-0** [comment]
Adds rust CI checks for package auditing, code coverage, unit testing, compilation (debug and release mode), and formatting

**Comment by ahuston-0** [comment]
2a5a396 removes an unused byteorder import. Double check that this can actually be removed, but it was enough to trigger a CI build :)

**Comment by ahuston-0** [comment]
Marking as ready for review, but asking that you keep the source branch for when I get caching actually working. i'll open another PR at that point

**Review by dkrautha — APPROVED** [review]
LGTM

**Pull request merged**
